### PR TITLE
Test HA and upgrade, fix logging relations, update bundles

### PR DESCRIPTION
**Pull request by johnsca**

### CODE REVIEW

**Comment by ktsakalozos** [comment]
I am not sure what the bundle-local.yaml (see 10-bundle.py) is supposed to have so I run the tests against bundle-dev.yaml.

Failed after 2+ hours with:
https://pastebin.canonical.com/155842/ on local lxc
and it remained blocked on https://pastebin.canonical.com/155840/

Not sure why the plugin remains blocked in upgrade action. Lets talk at sync there are a couple of points that i do not get on the test. Thanks

**Comment by kwmonroe** [comment]
LGTM

**Comment by andrewdmcleod** [comment]
For lzo error, please merge https://github.com/juju-solutions/layer-hadoop-base/pull/11

hadoop-upgrade was not (re)installing LZO.

**Comment by ktsakalozos** [comment]
I couldn't reproduce the issue reported above with the upgrade process being stuck. It worked fine this time.

**Pull request merged**
